#!/usr/bin/env bash

cd $(readlink -f $(dirname "$0"))

if [[ "$1" == "-v" || "$1" == "--verbose" ]]
then
    VERBOSE="-v"
    shift
else
    VERBOSE=
fi

# Get SSH_USER from config file
if [[ -r sgw.conf ]]
then
    source sgw.conf
else
    echo "Config file does not exist or is not readable" >&2
    exit 3
fi

IP="$(./do.sh ip)"

# start. do. stop.
./do.sh "$VERBOSE" -w start && {
    ./wait.sh on "$IP" "."
    ssh -Att "${SSH_USER}@${IP}" "$@"
}
./do.sh "$VERBOSE" stop
